# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

## Authentication parameters
## ref: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#setting-the-root-password-on-first-run
## ref: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#creating-a-database-on-first-run
## ref: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#creating-a-database-user-on-first-run
##
auth:
  ## @param auth.enablePostgresUser Assign a password to the "postgres" admin user. Otherwise, remote access will be blocked for this user
  ##
  enablePostgresUser: true
  ## @param auth.postgresPassword Password for the "postgres" admin user. Ignored if `auth.existingSecret` is provided
  ##
  postgresPassword: "$PGPASSWORD"
  ## @param auth.database Name for a custom database to create
  ##
  database: "$PGDATABASE"
primary:
  ## PostgreSQL Primary service configuration
  ##
  service:
    ## @param primary.service.type Kubernetes Service type
    ##
    type: NodePort
    ## Node ports to expose
    ## NOTE: choose port between <30000-32767>
    ## @param primary.service.nodePorts.postgresql Node port for PostgreSQL
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    nodePorts:
      postgresql: $PGPORT
  ## PostgreSQL Primary persistence configuration
  ##
  persistence:
    ## @param primary.persistence.size PVC Storage Request for PostgreSQL volume
    ##
    size: 4Gi
  initdb:
    scripts:
      00-test.sh: |
        echo "We're running initdb scripts"
      01-init-temporal.sql: |
        SELECT 'Hi we''re running the sql script';
        CREATE USER "$TEMPORAL_PGUSER" WITH PASSWORD '$TEMPORAL_PGPASSWORD';
        CREATE DATABASE "$TEMPORAL_PGDATABASE" OWNER "$TEMPORAL_PGUSER";
        CREATE DATABASE "${TEMPORAL_PGDATABASE}_visibility" OWNER "$TEMPORAL_PGUSER";

        /* Other dependency databases */
        CREATE DATABASE "hydradev";
        CREATE DATABASE "spicedbdev";
      02-test.sh: |
        echo "We're finished running initdb scripts"
