apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: temporal-gateway
    namespace: default
spec:
    selector:
      istio: ingressgateway
    servers:
    - port:
        number: 7233
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: temporal
    namespace: default
spec:
    hosts:
    - "*"
    gateways:
    - temporal-gateway
    http:
    - match:
      - uri:
          prefix: /
        route:
      - destination:
          host: temporal-frontend.default.svc.cluster.local
          port:
            number: 7233
